platform :ios, '13.0'

target 'William_STT_Runner' do
  pod 'LibTorch-Lite', '2.1.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # Exclude arm64 architecture for the simulator
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
  end
end